source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'sqlite3'


group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'haml', '3.1.7'
gem 'compass', '0.12.2'
gem 'devise', '2.1.2'
gem 'rspec', '2.12.0'
gem 'guard', '1.5.4'